dist: precise
language: node_js
sudo: false
script: sleep 100
after_success:
  - echo after_success
after_failure:
  - echo after_failure
after_script:
  - echo after_script
notifications:
    email: false
