matrix:
    include:
        - language: swift
        - language: generic
install: true
script:
    - "travis_retry travis_wait 2 awk 'BEGIN{print \"tada\"; exit 1}'"
    - "travis_wait 2 travis_retry awk 'BEGIN{print \"tada\"; exit 1}'"
    - "set -o pipefail"
    - "travis_retry travis_wait 2 awk 'BEGIN{print \"tada\"; exit 1}'"
    - "travis_wait 2 travis_retry awk 'BEGIN{print \"tada\"; exit 1}'"
    - "set -o pipefail && travis_retry travis_wait 2 awk 'BEGIN{print \"tada\"; exit 1}'"
    - "set -o pipefail && travis_wait 2 travis_retry awk 'BEGIN{print \"tada\"; exit 1}'"
notifications:
    email: false
