language: ruby
dist: precise
matrix:
    include:
        - env: image=gce
          sudo: required
        - env: image=ec2
          sudo: false
rvm: 2.3
install: true
script:
    - cat ~/build.sh
notifications:
  email: never

