language: ruby
sudo: required
matrix:
    include:
        - env: image=trusty
          dist: trusty
        - env: image=precise
          dist: precise

install: true
script: sudo find /sys/fs/cgroup/memory
notifications:
    email: never
