language: ruby
matrix:
    include:
        - os: linux
          sudo: false
          dist: trusty
          env: DIST=ec2-trusty
        - os: linux
          sudo: false
          dist: precise
          env: DIST=docker-precise
addons:
    mariadb:
        10.1
install: echo Ja
script:
  - "mysql -uroot -e 'SHOW VARIABLES LIKE \"%version%\";' || true"
  - "mysql -uroot -e 'select version()'"
  - ps aux | egrep 'mysql|maria'
