dist: precise
language: python
python: 2.7
sudo: false
install: true
script:
    - PYTHONPATH=$(pwd) python -c 'import math; print math.log(3)'
    - touch math.py
    - PYTHONPATH=$(pwd) python -c 'import math; print math.log(3)'
    - python -c 'import sys; print sys.path'
notifications:
    email: false
