language: ruby
matrix:
    include:
        - env: image=stable
          sudo: required
          group: stable
        - env: image=deprecated
          sudo: requird
          group: deprecated
dist: trusty
install: true
script:
- mount
- sleep 10
- "mysql -uroot -e 'SHOW VARIABLES'"
notifications:
  email: never
