language: ruby
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    env: DIST=trusty-stable
install: true
script:
- travis_wait 15 sh -c 'sleep 660' &
- sleep 630
notifications:
    email: never
