language: ruby
sudo: false
dist: trusty
install:
    - "git clone ssh://git@github.com/node-webot/wechat-api.git repo1 || true"
    - "git clone git@github.com/node-webot/wechat-api.git repo2 || true"
    - "git clone https://github.com/node-webot/wechat-api.git repo3 || true"
script: true
notifications:
    email: never
