dist: precise
language: elixir
sudo: false
before_install:
    - "phpenv global 5.6"
    - "composer self-update --stable && composer --version"
install: true
script: true
notifications:
    email: false
