language: ruby
sudo: required
dist: trusty
install: true
addons:
    firefox: "5.0.1"
script:
    - which firefox
    - ls -lR /tmp
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - firefox &
    - sleep 5
    - ps aux | grep firefox
notifications:
    email: never
