sudo: false
language: ruby
dist: trusty
group: stable
services:
    - mysql
install: true
script:
    - "{ ps aux | grep mysql; } || true"
    - "mysql -uroot -e 'SHOW VARIABLES LIKE \"%version%\";' || true"
notifications:
    email: false
