language: ruby
os: linux
sudo: false
dist: trusty
env: error_in:deploy
install: true
script: true
after_success: /bin/true
before_deploy: /bin/true
deploy:
    provide: script
    script: /bin/false
after_deploy: /bin/true
notifications:
    email: never
