dist: trusty
language: java
jdk: oraclejdk8
services:
    - mongodb
    - docker
sudo: true
install: true
script:
    - "head -n 1000 ~/.docker/config.json || true"
    - df -h
notifications:
    email: false
