language: ruby
matrix:
    include:
        - os: linux
          sudo: false
          dist: trusty
          env: DIST=ec2-trusty
        - os: linux
          sudo: false
          dist: precise
          env: DIST=docker-precise
install:
    - echo "-----BEGIN OPENSSH PRIVATE KEY-----" >>/tmp/key
    - echo "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW" >>/tmp/key
    - echo "QyNTUxOQAAACDDL9aYPcNmhNIKUkdPu8lwYyissnFRFZCBK3h2dXkehQAAAJCzU3k0s1N5" >>/tmp/key
    - echo "NAAAAAtzc2gtZWQyNTUxOQAAACDDL9aYPcNmhNIKUkdPu8lwYyissnFRFZCBK3h2dXkehQ" >>/tmp/key
    - echo "AAAEDOil4T2YfvCY/mmYlXq1Y20PG416oo5DeFTjWfMPxDUcMv1pg9w2aE0gpSR0+7yXBj" >>/tmp/key
    - echo "KKyycVEVkIEreHZ1eR6FAAAAC2pvZXBAam9lcHZkAQI=" >>/tmp/key
    - echo "-----END OPENSSH PRIVATE KEY-----" >>/tmp/key

script:
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/key
    - ssh-add /tmp/key
