language: ruby
sudo: required
matrix:
    include:
        - env: image=trusty
          dist: trusty
        - env: image=precise
          dist: precise

install: true
script:
    - ls -l /sys/fs/cgroup
    - sudo find /sys/fs/cgroup/memory
    - find /sys/fs/cgroup/memory
notifications:
    email: never
