language: generic
matrix:
    include:
        - env: run=openssl_updated
          addons:
              apt:
                  packages:
                      - openssl
        - env: run=default_ssl
dist: precise
sudo: false
install: openssl ciphers | tr : '\n' | sort
script:
    - wget https://repo.hex.pm/builds/elixir/v1.4.2.zip
    - curl -o /tmp/elixir https://repo.hex.pm/builds/elixir/v1.4.2.zip
notifications:
    email: false
