language: node_js

matrix:
  include:
  - os: linux
    dist: trusty
    node_js: "stable"
    sudo: required
    addons:
      apt:
        packages:
        - google-chrome-stable
install: true
script: true
notifications:
    email: false
