matrix:
    include:
        - language: swift
        - language: generic
install: true
script:
    - "travis_retry travis_wait 2 ls nosuchfile"
    - "travis_wait 2 travis_retry ls nosuchfile"
    - "set -o pipefail"
    - "travis_retry travis_wait 2 ls nosuchfile"
    - "travis_wait 2 travis_retry ls nosuchfile"
    - "set -o pipefail && travis_retry travis_wait 2 ls nosuchfile"
    - "set -o pipefail && travis_wait 2 travis_retry ls nosuchfile"
notifications:
    email: false
