language: ruby
os: linux
sudo: false
dist: trusty
env: error_in=after_success
install: true
script: true
after_success: /bin/false
before_deploy: /bin/true
deploy:
    provider: script
    script: /bin/true
after_deploy: /bin/true
notifications:
    email: never
