language: ruby
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          env: DIST=trusty-stable
          group: stable
        - os: linux
          sudo: required
          dist: trusty
          env: DIST=trusty-deprecated
          group: deprecated
install:
    - sudo apt-get install iotop sysstat procps
    - sudo apt-get install mysql-server-5.6 mysql-client-5.6 mysql-client-core-5.6

script:
    - "while sleep 30; do top -b -n 1 | grep -v root | head -n 20; done &"
    - sudo iotop --batch --time --delay=30 &
