dist: precise
sudo: false
sbt: 2.11.2
matrix:
    include:
        - language: java
        - language: scala
install: true
script: "sbt --version || sbt -version || true"
notifications:
  email: never

