language: ruby
dist: precise
matrix:
    include:
        - env: image=gce
          sudo: required
        - env: image=ec2
          sudo: false
rvm: 2.3.1
install: true
script:
    - rvm alias list
    - find $rvm_path
notifications:
  email: never

