language: elixir
elixir: 1.0.5
otp_release: 17.4
matrix:
    include:
        - env: run='update packages'
          sudo: false
          addons:
              apt:
                  packages:
                      #- libcurl3
                      #- libidn11
                      #- libldap-2.4-2
                      #- libldap-2.4-2
                      #- libgssapi-krb5-2
                      - libssl1.0.0
                      #- libgnutls26
                      #- libgcrypt11
                      #- libkrb5-3
                      #- libk5crypto3
                      #- libcomerr2
                      #- libkrb5support0
                      #- libtasn1-3
                      #- libsqlite3-0

        - env: run='no update binaries'
          sudo: false
dist: precise
install: true
script: true
notifications:
    email: false
