matrix:
    include:
        - env: image=precise_container
          sudo: false
          dist: precise
        - env: image=precise_sudo
          sudo: required
          dist: precise
        - env: image=trusty_container
          sudo: false
          dist: trusty
        - env: image=trusty_sudo
          sudo: required
          dist: trusty
install: true
language: php
php: 5.5
script:
  - php ssl.php
notifications:
    email: false
