language: generic
sudo: true
dist: trusty
addons:
    apt:
        packages:
            - postgresql
            - mysql-server
            - mysql-client
            - redis-server
install: true
script:
    - "mysql -uroot -e 'SHOW VARIABLES LIKE \"%version%\";' || true"
    - "psql -u postgres <<<'select * from version();'"
    - redis-cli INFO
notifications:
  email: never
