language: go

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          group: stable
          env: DIST=gce-trusty-stable
        - os: linux
          sudo: required
          dist: trusty
          group: deprecated
          env: DIST=gce-trusty-deprecated
install: go build prime.go
script: ./prime
notifications:
    email:
        false
