language: generic
matrix:
    include:
        - env: run='update packages'
          sudo: false
          addons:
              apt:
                  packages:
                      #- libcurl3
                      #- libidn11
                      #- libldap-2.4-2
                      #- libldap-2.4-2
                      #- libgssapi-krb5-2
                      - libssl1.0.0
                      #- libgnutls26
                      #- libgcrypt11
                      #- libkrb5-3
                      #- libk5crypto3
                      #- libcomerr2
                      #- libkrb5support0
                      #- libtasn1-3
                      #- libsqlite3-0

        - env: run='no update binaries'
          sudo: false
dist: precise
install:
    - "openssl ciphers | tr : '\n' | sort"
    - ./checkcurldeps.sh
script:
    - curl --version
    - wget --version
    - wget https://repo.hex.pm/builds/elixir/v1.4.2.zip
    - curl -o /tmp/elixir https://repo.hex.pm/builds/elixir/v1.4.2.zip
notifications:
    email: false
