dist: precise
language: python
python: 2.7
sudo: false
install: true
script:
    - touch math.py
    - PYTHONPATH=$TRAVIS_BUILD_DIR python -c 'import math; print math.log(3)'
notifications:
    email: false
