services:
  - riak           # basic version
  - rabbitmq
  - memcached
  - mysql          # default version, users. No sockets.
  - postgresql     # TODO: postgis, locales
  - mongodb        # version check
  - couchdb
  - redis-server
  - cassandra      # version check
  - neo4j          # version check
  - elasticsearch  # version check

addons:
    rethinkdb: "2.3.5"

install: true

script:
  - echo riak
  - "riak version"
  - "echo ...... mysql ......"
  - "ps aux | grep '[m]ysql' || true"
  - mysql -uroot -e 'SHOW VARIABLES LIKE "%version%";'
  - mysql -utravis -e 'SHOW VARIABLES LIKE "%version%";'
  - mysql -uroot -e 'select * from mysql.users;'
  - "echo ...... postgresql ......"
  - psql -Upostgres <<<'select * from version();'
  - psql -Upostgres <<<'select * from pg_catalog.pg_database;'
  - psql -Upostgres <<<'select * from pg_catalog.pg_user;'
  - mount # To check the ramfs
  - echo neo4j
  - curl http://localhost:7474/db/data/
  - "echo ......... elasticsearch ......."
  - curl http://localhost:9200/_nodes
  - "echo ......... cassandra ........"
  - "cqlsh -f <(echo show version)"
  - "cqlsh -f <(echo 'select * from system.local;')"
  - "echo ..... mongodb ......."
  - "mongo mydb_test --eval 'db.addUser(\"travis\", \"test\");' || true"
  - mongo --eval 'db.version()'


sudo: required

notifications:
  email: never

matrix:
  include:
  - env: image=edge_precise_go
    group: edge
    dist: precise
    language: go
  - env: image=stable_precise_go
    group: stable
    dist: precise
    language: go
  - env: image=edge_precise_java
    group: edge
    dist: precise
    language: java
  - env: image=stable_precise_java
    group: stable
    dist: precise
    language: java
  - env: image=edge_precise_node_js
    group: edge
    dist: precise
    language: node_js
  - env: image=stable_precise_node_js
    group: stable
    dist: precise
    language: node_js
  - env: image=edge_precise_perl
    group: edge
    dist: precise
    language: perl
  - env: image=stable_precise_perl
    group: stable
    dist: precise
    language: perl
  - env: image=edge_precise_php
    group: edge
    dist: precise
    language: php
  - env: image=stable_precise_php
    group: stable
    dist: precise
    language: php
  - env: image=edge_precise_python
    group: edge
    dist: precise
    language: python
  - env: image=stable_precise_python
    group: stable
    dist: precise
    language: python
  - env: image=edge_precise_ruby
    group: edge
    dist: precise
    language: ruby
  - env: image=stable_precise_ruby
    group: stable
    dist: precise
    language: ruby
