language: ruby
os: linux
sudo: false
dist: trusty
env: error_in=after_script
install: true
script: true
after_script: /bin/false
after_success: /bin/true
before_deploy: /bin/true
deploy:
    provider: script
    script: /bin/true
after_deploy: /bin/true
notifications:
    email: never
