language: node_js
node_js: "stable"

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - google-chrome-stable
install: true
script: true
notifications:
    email: false
