language: perl
dist: trusty
sudo: false
addons:
  browserstack:
    username: "username"
    access_key: "key"
    verbose: true

perl:
    - 5.24-shrplib
install: ls -l ~
script: cat ~/build.sh
notifications:
  email: never
