language: generic
matrix:
    include:
        - env: run=container_precise
          sudo: false
          #addons:
          #    apt:
          #        packages:
          #            - openssl
          #            - curl
          #            - wget
          #            - libcurl3
        - env: run=sudo_precise
          sudo: required
dist: precise
install:
    - "openssl ciphers | tr : '\n' | sort"
    - ./checkcurldeps.sh
script:
    - curl --version
    - wget --version
    - wget https://repo.hex.pm/builds/elixir/v1.4.2.zip
    - curl -o /tmp/elixir https://repo.hex.pm/builds/elixir/v1.4.2.zip
notifications:
    email: false
