matrix:
    include:
        - env: image=trusty-cont
          sudo: false
          dist: trusty
install: true
script:
    - travis_retry travis_wait 1 false
    - travis_wait travis_retry 1 false
    - set -o pipefail
    - travis_retry travis_wait 1 false
    - travis_wait travis_retry 1 false
notifications:
    email: false
