distL trusty
sudo: required
install: true
script:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo apt-key fingerprint 0EBFCD88
    - sudo add-apt-repository 'deb https://download.docker.com/linux/ubuntu trusty stable'
    - sudo apt-get update
    - "sudo apt-get install -o Dpkg::Options::=\"--force-confold\" --force-yes -y docker-ce"
    - docker --version
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get install docker-ce
    - docker --version
notifications:
  email: never

