dist: precise
language: node_js
sudo: false
script: sleep 100
after_success: echo after_success
after_failure: echo after_failure
before_deploy: echo before_deploy
deploy: echo deploy
after_deploy: echo after_deploy
after_script: echo after_script
notifications:
    email: false
